data.frame(
  Grouping_feature = c(
    rep("Voltinism", 6),
    rep("Feeding Mode", 10),
    rep("Locomotion", 8),
    rep("Respiration", 8),
    rep("Body size", 7),
    rep("Reproduction", 9)
  ),
  Freshwater_ecol = c(
    "Semivoltine",
    "Univoltine",
    "Bivoltine",
    "Trivoltine",
    "Multivoltine",
    "Flexible",
    "Shredder",
    "Miner",
    "Xylophagus",
    "Gatherer",
    "Active filterer",
    "Passive filterer",
    "Grazer",
    "Predator",
    "Parasite",
    "Other",
    "Swimming/scating",
    "Swimming/diving",
    "Burrowing/boring",
    "Sprawling/walking",
    "(semi) sessil",
    "Other",
    NA,
    NA,
    "Tegument",
    "Gill",
    "Plastron",
    "Spiracle",
    "aerial",
    "Hydrostatic vesicle",
    "Tapping (air stores of aq. plants)",
    "Excursion/Extension (to surface)",
    rep(NA, 7),
    "ovovivipar",
    "free isolated eggs",
    "cemented isolated eggs",
    "fixed clutches",
    "free clutches",
    "clutches in vegetation",
    "terrestrial clutches",
    "asexual",
    "parasitic"
  ),
  Tachet = c(
    "Semivoltine",
    "Univoltine",
    "Polyvoltine",
    NA,
    NA,
    NA,
    "Shredder",
    "Deposit-feeder",
    "Absorber",
    "Filter-feeder",
    "Scraper",
    "Predator",
    "Parasite",
    "Piercer (plants or animals)",
    NA,
    NA,
    "Surface swimmer",
    "Full water swimmer",
    "Burrower",
    "Crawler",
    "Temporarily attachted",
    "Permanently attached",
    "Interstitial",
    "Flier",
    "Tegument",
    "Gill",
    "Plastron",
    "Spiracle (aerial)",
    "Hydrostatic vesicle (aerial)",
    NA,
    NA,
    NA,
    "<= 0.25cm",
    "> 0.25 - 0.5cm",
    "> 0.5- 1cm",
    "> 1 – 2 cm",
    "2 – 4 cm",
    "4 – 8 cm",
    "> 8 cm",
    "ovoviviparity",
    "isolated eggs, free",
    "isolated eggs, cemented",
    "clutches, cemented or fixed",
    "clutches, free",
    "clutches, in vegetation",
    "clutches, terrestrial",
    "asexual reproduction",
    NA
  ),
  Harmonized_traits = c(
    "Semivoltine",
    "Univoltine",
    "Bi/Multivoltine",
    NA,
    NA,
    NA,
    "Shredder",
    "Gatherer",
    "Filterer",
    "Herbivore",
    "Predator",
    "Parasite",
    NA,
    NA,
    NA,
    NA,
    "Swimmer",
    "Burrower",
    "Crawler",
    "Sessil",
    NA,
    NA,
    NA,
    NA,
    "Tegument",
    "Gills",
    "Plastron, spiracle",
    NA,
    NA,
    NA,
    NA,
    NA,
    "Small (< 1 cm)",
    "Medium (>= 1cm - 2 cm)",
    "Large (>= 2 cm)",
    rep(NA, 4),
    "ovoviviparity",
    "aquatic eggs",
    "terrestrial eggs",
    rep(NA,6)
  )
) %>% 
  xtable_wo_rownames()
